# Generated by Django 5.2.9 on 2026-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('cp', models.CharField(choices=[('Typical Angina', 'Typical Angina'), ('Atypical Angina', 'Atypical Angina'), ('Non-Anginal Pain', 'Non-Anginal Pain'), ('Asymptomatic', 'Asymptomatic')], max_length=50, verbose_name='Chest Pain Type')),
                ('trestbps', models.IntegerField(verbose_name='Resting Blood Pressure')),
                ('chol', models.IntegerField(verbose_name='Cholesterol')),
                ('fbs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, verbose_name='Fasting Blood Sugar > 120 mg/dl')),
                ('restecg', models.CharField(choices=[('Normal', 'Normal'), ('ST-T abnormality', 'ST-T abnormality'), ('Left Ventricular Hypertrophy', 'Left Ventricular Hypertrophy')], max_length=50, verbose_name='Resting ECG')),
                ('thalach', models.IntegerField(verbose_name='Maximum Heart Rate Achieved')),
                ('exang', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, verbose_name='Exercise Induced Angina')),
                ('oldpeak', models.FloatField(verbose_name='ST Depression Induced by Exercise')),
                ('slope', models.CharField(choices=[('Upsloping', 'Upsloping'), ('Flat', 'Flat'), ('Downsloping', 'Downsloping')], max_length=20, verbose_name='Slope of Peak Exercise ST Segment')),
                ('ca', models.IntegerField(verbose_name='Number of Major Vessels Colored by Fluoroscopy')),
                ('thal', models.CharField(choices=[('Normal', 'Normal'), ('Fixed Defect', 'Fixed Defect'), ('Reversible Defect', 'Reversible Defect')], max_length=50, verbose_name='Thalassemia')),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
