# Generated by Django 5.2.9 on 2026-02-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('bmi', models.FloatField()),
                ('hbA1c_level', models.FloatField()),
                ('blood_glucose_level', models.IntegerField()),
                ('hypertension', models.IntegerField()),
                ('heart_disease', models.IntegerField()),
                ('smoking_history', models.CharField(max_length=20)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiverAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('total_bilirubin', models.FloatField()),
                ('direct_bilirubin', models.FloatField()),
                ('alkaline_phosphotase', models.IntegerField()),
                ('alamine_aminotransferase', models.IntegerField()),
                ('aspartate_aminotransferase', models.IntegerField()),
                ('total_protiens', models.FloatField()),
                ('albumin', models.FloatField()),
                ('albumin_and_globulin_ratio', models.FloatField()),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrinalysisAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('transparency', models.CharField(max_length=30)),
                ('glucose', models.CharField(max_length=30)),
                ('protein', models.CharField(max_length=30)),
                ('ph', models.FloatField()),
                ('specific_gravity', models.FloatField()),
                ('wbc', models.CharField(max_length=30)),
                ('rbc', models.CharField(max_length=30)),
                ('epithelial_cells', models.CharField(max_length=30)),
                ('mucous_threads', models.CharField(max_length=30)),
                ('amorphous_urates', models.CharField(max_length=30)),
                ('bacteria', models.CharField(max_length=30)),
                ('diagnosis', models.CharField(blank=True, max_length=50, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
