# Generated by Django 5.2.9 on 2026-02-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diabetesassessment_liverassessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidneyAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('bp', models.FloatField(verbose_name='Blood Pressure')),
                ('sg', models.FloatField(verbose_name='Specific Gravity')),
                ('al', models.FloatField(verbose_name='Albumin')),
                ('su', models.FloatField(verbose_name='Sugar')),
                ('rbc', models.CharField(max_length=10, verbose_name='Red Blood Cells')),
                ('pc', models.CharField(max_length=10, verbose_name='Pus Cell')),
                ('pcc', models.CharField(max_length=10, verbose_name='Pus Cell Clumps')),
                ('ba', models.CharField(max_length=10, verbose_name='Bacteria')),
                ('bgr', models.FloatField(verbose_name='Blood Glucose Random')),
                ('bu', models.FloatField(verbose_name='Blood Urea')),
                ('sc', models.FloatField(verbose_name='Serum Creatinine')),
                ('sod', models.FloatField(verbose_name='Sodium')),
                ('pot', models.FloatField(verbose_name='Potassium')),
                ('hemo', models.FloatField(verbose_name='Hemoglobin')),
                ('pcv', models.FloatField(verbose_name='Packed Cell Volume')),
                ('wc', models.FloatField(verbose_name='White Blood Cell Count')),
                ('rc', models.FloatField(verbose_name='Red Blood Cell Count')),
                ('htn', models.CharField(max_length=5, verbose_name='Hypertension')),
                ('dm', models.CharField(max_length=5, verbose_name='Diabetes Mellitus')),
                ('cad', models.CharField(max_length=5, verbose_name='Coronary Artery Disease')),
                ('appet', models.CharField(max_length=10, verbose_name='Appetite')),
                ('pe', models.CharField(max_length=5, verbose_name='Pedal Edema')),
                ('ane', models.CharField(max_length=5, verbose_name='Anemia')),
                ('classification', models.CharField(blank=True, max_length=20, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
