# Generated by Django 6.0.2 on 2026-02-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_urinalysisassessment_diabetesassessment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesassessment',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heartassessment',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kidneyassessment',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liverassessment',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
